name: Dockerfile Lint

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - dso-111

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: docker://hadolint/hadolint:3.1.0
        with:
          args: Dockerfile
