name: Dockerfile Lint and Docker to ECR

on:
  push:
    branches:
      - slack

jobs:
  lint-and-push:
    name: Lint Dockerfile and Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Tag Docker image
        run: docker tag my-image:latest 592524167743.dkr.ecr.us-west-2.amazonaws.com/bar:latest

      - name: Push Docker image to Amazon ECR
        run: docker push 592524167743.dkr.ecr.us-west-2.amazonaws.com/bar:latest

      - name: Send Slack notification
        uses: slack/webhook-action@v2
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          method: POST
          payload: '{"text": "Docker image has been pushed to ECR successfully!"}'
