name: Dockerfile Lint

on:
  push:
    branches:
      - main
      - dso-111

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
         dockerfile: Dockerfile


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Tag Docker image
        run: docker tag my-image:latest 592524167743.dkr.ecr.us-west-2.amazonaws.com/bar:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 592524167743.dkr.ecr.us-west-2.amazonaws.com/bar:latest
